npmの学習コンテンツ完了
rikarin0308/tutorial pull request #6
Opened 2022-03-14 08:38 UTC by rikarin0308

@hyamakawa 
npmの学習アウトプットを格納しました。
よろしくお願いします。

2022-03-14 10:34 UTC, hyamakawa requested changes
@rikarin0308 みました！ちょっとだけ修正コメントします！また明日！

2022-03-15 00:39 UTC, rikarin0308 commented on npm/.gitignore
> +node_modules
修正します。

2022-03-15 00:40 UTC, rikarin0308 commented on npm/momentja.js
> +console.log(thistime2);
「改行」忘れないように気を付けます。

2022-03-15 01:49 UTC, rikarin0308 commented on npm/momentja.js
> +console.log(thistime2);
改行追加しました。

2022-03-15 01:49 UTC, rikarin0308 commented on npm/.gitignore
> +node_modules
改行追加しました。

2022-03-15 02:11 UTC, hyamakawa commented
@rikarin0308 みました、LGTM!

2022-03-15 02:15 UTC, merged