本の情報を登録・更新できるように修正した
rikarin0308/tutorial pull request #7
Opened 2022-03-19 00:53 UTC by rikarin0308

課題その①「本の情報を登録・更新できるようにする（クライアントのみ）」の修正しました。よろしくお願いします。
（登録画面の上のほうに確認で追加したところ（Vue.js!～）が残ってますが、課題おわってから最後に削除します。）

2022-03-20 23:07 UTC, hyamakawa requested changes
@もりりん

みましたー。コメントもしてます、確認お願いします 🙇   
ソースをmodern-tから取ってきて、そのまま課題に取り掛かったので差分が全部出ちゃってますねｗ  
動作確認した段階で一度masterにpushしておくとよさそうですね、今後の人は。。。

2022-03-20 23:07 UTC, hyamakawa commented on web_application/src/components/books.vue
> +      this.upsertParam.controlNo = ''
【参考】
初期化は色々やり方あると思いますが、  
この処理を `あるオブジェクトのプロパティに一律空文字を設定する処理` と読み替えるなら  
こんな感じの処理が書けたりするのかな〜と思います。

``` javascript
for (key in upsertParam) {
  this.upsertParam[key] = ''
}
```

※オブジェクトのプロパティにアクセスする方法は `xxx.yyy` だけじゃなくて、`xxx[yyy]` というやり方もあるんだというところは覚えておいてもらえるといいかなと思います！

2022-03-22 01:59 UTC, rikarin0308 commented on web_application/src/components/books.vue
> +      this.upsertParam.controlNo = ''
for in で初期化してみました。便利ですね。覚えておきます！

2022-03-22 02:02 UTC, rikarin0308 commented on web_application/src/components/books.vue
> +          this.$set(this.books, index, {
同じ内容のところは関数にした方がよいのですね。意識します。

2022-03-22 02:03 UTC, rikarin0308 commented on web_application/src/components/books.vue
> +      for (var index = 0; index <= this.books.length - 1; index++) {
letを使うように修正しました。
＞const で宣言されてるものだと 値変わってかない項目なんだな
＞let で宣言されてるものだと 値変わってく変数なんやな
なるほどです。見やすいコード、、

2022-03-22 02:04 UTC, rikarin0308 commented on web_application/src/components/books.vue
> +          this.$set(this.books, index, {
純粋なjavascriptで書いてみました。確認お願いします。

2022-03-22 02:28 UTC, hyamakawa commented on web_application/src/components/books.vue
> +      this.upsertParam.controlNo = ''
🙆‍♂️

2022-03-22 02:31 UTC, hyamakawa commented on web_application/src/components/books.vue
> +      for (index = 0; index <= this.books.length - 1; index++) {
`for (let index = 0; index <= this.books.length - 1; index++) {`

って書いてもらえれば。。。

2022-03-22 02:34 UTC, hyamakawa commented on web_application/src/components/books.vue
> +          this.$set(this.books, index, {
確認しました。
ここもfor in でかけそう？

2022-03-22 02:34 UTC, hyamakawa commented
@rikarin0308 確認してコメントしましたー

2022-03-22 05:01 UTC, rikarin0308 commented on web_application/src/components/books.vue
> +      for (index = 0; index <= this.books.length - 1; index++) {
最初、指摘のように書いていたのですが、エラーがでたので、for文の外に出してみました。
もしかして、for文の中だけでなくて、あとでindexを使用してるからですか？？
```
Failed to compile.

./src/components/books.vue
Module Error (from ./node_modules/eslint-loader/index.js):
error: 'index' is not defined (no-undef) at src\components\books.vue:314:30:
  312 |         }
  313 |       }
> 314 |       console.log(this.books[index])
      |                              ^
  315 |       console.log(index)
  316 |       console.log(this.books.length)
  317 |       if (index === this.books.length) {


error: 'index' is not defined (no-undef) at src\components\books.vue:315:19:
  313 |       }
  314 |       console.log(this.books[index])
> 315 |       console.log(index)
      |                   ^
  316 |       console.log(this.books.length)
  317 |       if (index === this.books.length) {
  318 |         this.books.push({


error: 'index' is not defined (no-undef) at src\components\books.vue:317:11:
  315 |       console.log(index)
  316 |       console.log(this.books.length)
> 317 |       if (index === this.books.length) {
      |           ^
  318 |         this.books.push({
  319 |           controlNo: this.upsertParam.controlNo,
  320 |           category: this.upsertParam.category,


3 errors found.
```

2022-03-22 05:28 UTC, rikarin0308 commented on web_application/src/components/books.vue
> +          this.$set(this.books, index, {
for inを使って書いてみました。
「key」は最後の初期化（334）でも使ってますが、問題ないですか？

2022-03-22 05:29 UTC, rikarin0308 commented
@hyamakawa 
修正しました。確認お願いします！

2022-03-22 05:44 UTC, hyamakawa commented on web_application/src/components/books.vue
> +      for (index = 0; index <= this.books.length - 1; index++) {
そうでしたね、forで回したindexを後続処理で使ってるんでした。
失礼しました。。。

なので、この書き方で問題ないです！

2022-03-22 05:49 UTC, hyamakawa commented on web_application/src/components/books.vue
> +          this.$set(this.books, index, {
問題ないです。

keyはそれぞれのforループの中がのスコープになるので。

2022-03-22 05:50 UTC, hyamakawa commented
@rikarin0308 LGTM!!!!!!!!!!!!

2022-03-22 05:56 UTC, merged